name: IP Optimizer
on:
  workflow_dispatch:
  schedule:
    - cron: '0 21 * * *'  # UTC 21:00 = 北京时间5:00
    - cron: '0 9 * * *'   # UTC 9:00 = 北京时间17:00

jobs:
  optimize:
    runs-on: ubuntu-latest
    env:
      MODE: TCP
      PORT: 443
      RTT_RANGE: "40~250"
      LOSS_MAX: 10
      THREADS: 50         # 默认并发数
      IP_POOL_SIZE: 100000 # IP池总大小 [新增]
      TEST_IP_COUNT: 200  # 实际测试IP数量 [新增]
      SPEED_URL: "https://speed.cloudflare.com/__down?bytes=10000000"
      CLOUDFLARE_IPS_URL: "www.cloudflare.com/ips-v4"
      CUSTOM_IPS_FILE: "custom_ips.txt" # 自定义IP池文件

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install requests numpy tqdm
        sudo apt-get update
        sudo apt-get install -y net-tools

    - name: Run IP Optimizer
      run: python ip_optimizer.py

    - name: Commit results
      run: |
        git config user.name "github-actions"
        git config user.email "actions@github.com"
        git add results/
        git commit -m "Auto: Update optimized IPs"
        git push
